theme: minima
title: King of ARM
email: mattias@kingofarm.com
description: King of ARM is a how-to archive for working with ARM templates
url: http://www.kingofarm.com
google_analytics: UA-150949537-1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Disqus Comments
disqus:
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: kingofarm
